# Generated by Django 4.1.2 on 2022-10-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
                ('count_favor', models.IntegerField(default=0)),
                ('count_contra', models.IntegerField(default=0)),
                ('count_null', models.IntegerField(default=0)),
            ],
        ),
    ]
