# Generated by Django 4.1.2 on 2022-10-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emision_Votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votaciones',
            name='count_total',
            field=models.IntegerField(default=0),
        ),
    ]
